

stages:

  train:
    cmd: uv run python -m ai.scripts.train
    deps:
      - src/ai/scripts/train.py
    outs:
      - model_checkpoint

  # evaluate:
  #   cmd: python scripts/evaluate.py
  #   deps:
  #     - scripts/evaluate.py
